### ISSUE TITLE
[RFC] Recursive option for loading images into ImageManager & others

### ISSUE THREAD

**Issue by mattfelsen** [bluecadet/Cinder-BluecadetUtils#19]
In my top level `BaseApp` subclass I have the `ImageManager` load a bunch of folders upfront like so:

```c++
ImageManager::getInstance()->loadAllImagesInDirectory("images");
ImageManager::getInstance()->loadAllImagesInDirectory("ui");
ImageManager::getInstance()->loadAllImagesInDirectory("ui/arrow-sequence");
ImageManager::getInstance()->loadAllImagesInDirectory("ui/progress-indicator_white_120");
```

Each time I add a new image sequence (and therefore folder) I always forget to add another line here, but it'd be nice to not have to 😄 Perhaps we could do something like...

- `loadAllImagesInDirectory(const std::string &directoryName, bool recursive = false)`
- `loadAllImagesInDirectoryRecursive(const std::string &directoryName)`

Or similar. Thoughts?

**Comment by benjaminbojko** [comment]
Resolved in #20
